/**
 * serviços da mimo.
 * preços são "a partir de" - valores reais devem ser confirmados.
 */

import type { Service } from '../types'

export const SERVICES: Array<Service> = [
  {
    id: 'salao',
    slug: 'salao',
    title: 'Salão',
    description: 'Cortes, coloração e tratamentos capilares personalizados para todos os tipos de cabelo.',
    shortDescription: 'Cortes e coloração que valorizam seu estilo único',
    price: 'A partir de R$ 80',
    image: '/images/servicos/salao/SALAO_HEADER.webp',
    imageAlt: 'Salão de beleza Mimo - cortes e coloração',
    benefits: [
      'Cortes personalizados para seu tipo de cabelo',
      'Coloração com técnicas modernas',
      'Tratamentos capilares',
      'Profissionais especializados em cabelos cacheados e crespos',
    ],
    procedures: [
      { name: 'Mimo Cut', image: '/images/servicos/salao/MimoCut.webp', imageAlt: 'Mimo Cut - corte de cabelo' },
      { name: 'Mimo Gloss', image: '/images/servicos/salao/MimoGloss.webp', imageAlt: 'Mimo Gloss - gloss capilar' },
      { name: 'Amonia Free', image: '/images/servicos/salao/AmoniaFree.webp', imageAlt: 'Coloração Amonia Free' },
      { name: 'Blond', image: '/images/servicos/salao/Blond.webp', imageAlt: 'Coloração Blond' },
      { name: 'Full Blond', image: '/images/servicos/salao/FullBlond.webp', imageAlt: 'Coloração Full Blond' },
      { name: 'Full Fantasy', image: '/images/servicos/salao/FullFantasy.webp', imageAlt: 'Coloração Full Fantasy' },
      { name: 'Ombre', image: '/images/servicos/salao/Ombre.webp', imageAlt: 'Coloração Ombre' },
      { name: 'Royal', image: '/images/servicos/salao/Royal.webp', imageAlt: 'Coloração Royal' },
      { name: 'Ruivo Deluxe', image: '/images/servicos/salao/RuivoDeluxe.webp', imageAlt: 'Coloração Ruivo Deluxe' },
      { name: 'Ruivo Mimo', image: '/images/servicos/salao/RuivoMimo.webp', imageAlt: 'Coloração Ruivo Mimo' },
      { name: 'Summer', image: '/images/servicos/salao/Summer.webp', imageAlt: 'Coloração Summer' },
      { name: 'Tonalização', image: '/images/servicos/salao/Tonalização.webp', imageAlt: 'Tonalização capilar' },
    ],
  },
  {
    id: 'esmalteria',
    slug: 'esmalteria',
    title: 'Esmalteria',
    description: 'Manicure e pedicure com esmaltação em gel, duradoura e de alta qualidade.',
    shortDescription: 'Unhas impecáveis que duram semanas',
    price: 'A partir de R$ 50',
    image: '/images/servicos/esmalteria/ESMALTERIA_HEADER.webp',
    imageAlt: 'Esmalteria Mimo - manicure e pedicure',
    benefits: [
      'Esmaltação em gel duradoura',
      'Manicure e pedicure completos',
      'Cuidados com cutículas',
      'Designs personalizados',
    ],
    procedures: [
      { name: 'Porcelana', image: '/images/servicos/esmalteria/PORCELANA.webp', imageAlt: 'Porcelana' },
      { name: 'Blindagem de Gel', image: '/images/servicos/esmalteria/banho_gel.webp', imageAlt: 'Blindagem de gel' },
      { name: 'Alongamento de Polygel com Molde F1', image: '/images/servicos/esmalteria/polygel-molde-f1.webp', imageAlt: 'Alongamento de polygel com molde F1' },
    ],
  },
  {
    id: 'cilios',
    slug: 'cilios',
    title: 'Cílios e Design',
    description: 'Design de sobrancelhas, brow lamination e lash lift com técnicas que garantem resultado natural e duradouro.',
    shortDescription: 'Sobrancelhas perfeitas e cílios definidos',
    price: 'A partir de R$ 120',
    image: '/images/servicos/cilios/header_categoria_ciliosedesign.webp',
    imageAlt: 'Cílios e Design Mimo',
    benefits: [
      'Design de sobrancelhas personalizado',
      'Brow lamination para sobrancelhas definidas',
      'Lash lift para cílios curvados',
      'Resultado natural e duradouro',
      'Técnicas modernas e seguras',
    ],
    procedures: [
      { name: 'Design Novo', image: '/images/servicos/cilios/designnovo.webp', imageAlt: 'Design de sobrancelhas novo' },
      { name: 'Design Sobrancelha', image: '/images/servicos/cilios/designsob2r.webp', imageAlt: 'Design de sobrancelhas' },
      { name: 'Lash Lifting', image: '/images/servicos/cilios/lashliftingcilios.webp', imageAlt: 'Lash Lifting' },
      { name: 'Lift Sobrancelha', image: '/images/servicos/cilios/liftsobrancelha.webp', imageAlt: 'Brow lamination - lift de sobrancelhas' },
    ],
  },
  {
    id: 'micropigmentacao',
    slug: 'micropigmentacao',
    title: 'Micropigmentação',
    description: 'Micropigmentação de sobrancelhas e outras áreas com técnicas que garantem resultado natural e duradouro.',
    shortDescription: 'Sobrancelhas perfeitas que duram',
    price: 'A partir de R$ 400',
    image: '/images/servicos/micro/header.webp',
    imageAlt: 'Micropigmentação Mimo',
    benefits: [
      'Micropigmentação de sobrancelhas',
      'Resultado natural e duradouro',
      'Técnicas modernas',
      'Retoque após 30 dias',
      'Micropigmentação labial',
    ],
    procedures: [
      { name: 'Nanoblading', image: '/images/servicos/micro/Microblading.webp', imageAlt: 'Nanoblading de sobrancelhas' },
      { name: 'Micropigmentação Labial', image: '/images/servicos/micro/lips.webp', imageAlt: 'Micropigmentação labial' },
    ],
  },
  {
    id: 'estetica-facial',
    slug: 'estetica-facial',
    title: 'Estética Facial',
    description: 'Tratamentos faciais personalizados para todos os tipos de pele com técnicas modernas e produtos de alta qualidade.',
    shortDescription: 'Pele radiante e cuidada',
    price: 'A partir de R$ 150',
    image: '/images/servicos/facial/FACIAL_HEADER.webp',
    imageAlt: 'Estética facial Mimo',
    benefits: [
      'Limpeza de pele profunda',
      'Tratamentos personalizados',
      'Produtos de alta qualidade',
      'Profissionais especializados',
      'Microagulhamento',
      'Peelings químicos',
    ],
    procedures: [
      { name: 'Limpeza de Pele Mimo', image: '/images/servicos/facial/LIMPEZAMIMO.webp', imageAlt: 'Limpeza de pele Mimo' },
      { name: 'Limpeza de Pele Mimo VIP', image: '/images/servicos/facial/MIMOVIP.webp', imageAlt: 'Limpeza de pele Mimo VIP' },
      { name: 'Peeling Químico', image: '/images/servicos/facial/QUIMICO.webp', imageAlt: 'Peeling químico' },
      { name: 'Microagulhamento', image: '/images/servicos/facial/microagulhamento.webp', imageAlt: 'Microagulhamento facial' },
      { name: 'Depilação Facial', image: '/images/servicos/facial/depilacao_egipcia.webp', imageAlt: 'Depilação facial' },
    ],
  },
  {
    id: 'estetica-corporal',
    slug: 'estetica-corporal',
    title: 'Estética Corporal',
    description: 'Tratamentos corporais para bem-estar e cuidados com o corpo com técnicas modernas e equipamentos de última geração.',
    shortDescription: 'Cuidados completos para o corpo',
    price: 'A partir de R$ 200',
    image: '/images/servicos/corporal/CORPORAL_HEADER.webp',
    imageAlt: 'Estética corporal Mimo',
    benefits: [
      'Tratamentos personalizados',
      'Técnicas modernas',
      'Foco em bem-estar',
      'Profissionais especializados',
      'Equipamentos de última geração',
    ],
    procedures: [
      { name: 'Drenagem Linfática', image: '/images/servicos/corporal/linfatica.webp', imageAlt: 'Drenagem linfática' },
      { name: 'Massagem Relaxante', image: '/images/servicos/corporal/relaxante.webp', imageAlt: 'Massagem relaxante' },
      { name: 'Massagem Modeladora', image: '/images/servicos/corporal/modeladora.webp', imageAlt: 'Massagem modeladora' },
      { name: 'Radiofrequência', image: '/images/servicos/corporal/radiofrequencia.webp', imageAlt: 'Radiofrequência corporal' },
      { name: 'Corrente Russa', image: '/images/servicos/corporal/Corrente-Russa.webp', imageAlt: 'Corrente russa' },
      { name: 'Pump Up', image: '/images/servicos/corporal/pump.webp', imageAlt: 'Pump Up corporal' },
      { name: 'Ultrassom', image: '/images/servicos/corporal/ultrassom.webp', imageAlt: 'Ultrassom estético' },
      { name: 'Endermoterapia', image: '/images/servicos/corporal/endermoterapia.webp', imageAlt: 'Endermoterapia' },
    ],
  },
]

