/**
 * serviços da mimo.
 * preços são "a partir de" - valores reais devem ser confirmados.
 */

import type { Service } from '../types'

export const SERVICES: Array<Service> = [
  {
    id: 'salao',
    slug: 'salao',
    title: 'Salão',
    description: 'Cortes, coloração e tratamentos capilares personalizados para todos os tipos de cabelo.',
    shortDescription: 'Cortes e coloração que valorizam seu estilo único',
    price: 'A partir de R$ 80',
    image: '/images/servicos/salao/SALAO_HEADER.webp',
    imageAlt: 'Salão de beleza Mimo - cortes e coloração',
    benefits: [
      'Cortes personalizados para seu tipo de cabelo',
      'Coloração com técnicas modernas',
      'Tratamentos capilares',
      'Profissionais especializados em cabelos cacheados e crespos',
    ],
    procedures: [
      { name: 'Mimo Cut', image: '/images/servicos/salao/MimoCut.webp', imageAlt: 'Mimo Cut - corte de cabelo' },
      { name: 'Mimo Gloss', image: '/images/servicos/salao/MimoGloss.webp', imageAlt: 'Mimo Gloss - gloss capilar' },
      { name: 'Amonia Free', image: '/images/servicos/salao/AmoniaFree.webp', imageAlt: 'Coloração Amonia Free' },
      { name: 'Blond', image: '/images/servicos/salao/Blond.webp', imageAlt: 'Coloração Blond' },
      { name: 'Full Blond', image: '/images/servicos/salao/FullBlond.webp', imageAlt: 'Coloração Full Blond' },
      { name: 'Full Fantasy', image: '/images/servicos/salao/FullFantasy.webp', imageAlt: 'Coloração Full Fantasy' },
      { name: 'Ombre', image: '/images/servicos/salao/Ombre.webp', imageAlt: 'Coloração Ombre' },
      { name: 'Royal', image: '/images/servicos/salao/Royal.webp', imageAlt: 'Coloração Royal' },
      { name: 'Ruivo Deluxe', image: '/images/servicos/salao/RuivoDeluxe.webp', imageAlt: 'Coloração Ruivo Deluxe' },
      { name: 'Ruivo Mimo', image: '/images/servicos/salao/RuivoMimo.webp', imageAlt: 'Coloração Ruivo Mimo' },
      { name: 'Summer', image: '/images/servicos/salao/Summer.webp', imageAlt: 'Coloração Summer' },
      { name: 'Tonalização', image: '/images/servicos/salao/Tonalização.webp', imageAlt: 'Tonalização capilar' },
    ],
  },
  {
    id: 'esmalteria',
    slug: 'esmalteria',
    title: 'Esmalteria',
    description: 'Manicure e pedicure com esmaltação em gel, duradoura e de alta qualidade.',
    shortDescription: 'Unhas impecáveis que duram semanas',
    price: 'A partir de R$ 50',
    image: '/images/servicos/esmalteria/ESMALTERIA_HEADER.webp',
    imageAlt: 'Esmalteria Mimo - manicure e pedicure',
    benefits: [
      'Esmaltação em gel duradoura',
      'Manicure e pedicure completos',
      'Cuidados com cutículas',
      'Designs personalizados',
    ],
    procedures: [
      { name: 'Gel com Molde', image: '/images/servicos/esmalteria/GELCOMMOLDE.webp', imageAlt: 'Gel com molde' },
      { name: 'Gel com Protese', image: '/images/servicos/esmalteria/GELCOMPROTESE.webp', imageAlt: 'Gel com prótese' },
      { name: 'Acrigel com Molde', image: '/images/servicos/esmalteria/ACRIGELCOMMOLDE.webp', imageAlt: 'Acrigel com molde' },
      { name: 'Acrigel com Protese', image: '/images/servicos/esmalteria/ACRIGELCOMPROTESE.webp', imageAlt: 'Acrigel com prótese' },
      { name: 'Fibra de Vidro', image: '/images/servicos/esmalteria/FIBRADEVIDRO.webp', imageAlt: 'Fibra de vidro' },
      { name: 'Porcelana', image: '/images/servicos/esmalteria/PORCELANA.webp', imageAlt: 'Porcelana' },
      { name: 'Banho de Gel', image: '/images/servicos/esmalteria/banho_gel.webp', imageAlt: 'Banho de gel' },
      { name: 'Banho de Acrigel', image: '/images/servicos/esmalteria/banho_agrigel.webp', imageAlt: 'Banho de acrigel' },
    ],
  },
  {
    id: 'cilios',
    slug: 'cilios',
    title: 'Cílios e Design',
    description: 'Alongamento de cílios fio a fio e design de sobrancelhas com técnicas que garantem resultado natural e duradouro.',
    shortDescription: 'Cílios volumosos e sobrancelhas perfeitas',
    price: 'A partir de R$ 120',
    image: '/images/servicos/cilios/header_categoria_ciliosedesign.webp',
    imageAlt: 'Cílios e Design Mimo',
    benefits: [
      'Alongamento fio a fio',
      'Resultado natural e duradouro',
      'Manutenção a cada 3 semanas',
      'Técnicas modernas e seguras',
      'Design de sobrancelhas',
    ],
    procedures: [
      { name: 'Mimo', image: '/images/servicos/cilios/mimo.webp', imageAlt: 'Cílios Mimo' },
      { name: 'Mimo Mega', image: '/images/servicos/cilios/mimomega.webp', imageAlt: 'Cílios Mimo Mega' },
      { name: 'Super Mimo', image: '/images/servicos/cilios/supermimo.webp', imageAlt: 'Cílios Super Mimo' },
      { name: 'Volume Russo', image: '/images/servicos/cilios/volumerusso.webp', imageAlt: 'Volume Russo' },
      { name: 'Design Novo', image: '/images/servicos/cilios/designnovo.webp', imageAlt: 'Design de sobrancelhas novo' },
      { name: 'Design Sobrancelha', image: '/images/servicos/cilios/designsob2r.webp', imageAlt: 'Design de sobrancelhas' },
      { name: 'Lash Lifting', image: '/images/servicos/cilios/lashliftingcilios.webp', imageAlt: 'Lash Lifting' },
      { name: 'Lift Sobrancelha', image: '/images/servicos/cilios/liftsobrancelha.webp', imageAlt: 'Lift de sobrancelhas' },
    ],
  },
  {
    id: 'micropigmentacao',
    slug: 'micropigmentacao',
    title: 'Micropigmentação',
    description: 'Micropigmentação de sobrancelhas e outras áreas com técnicas que garantem resultado natural e duradouro.',
    shortDescription: 'Sobrancelhas perfeitas que duram',
    price: 'A partir de R$ 400',
    image: '/images/servicos/micro/header.webp',
    imageAlt: 'Micropigmentação Mimo',
    benefits: [
      'Micropigmentação de sobrancelhas',
      'Resultado natural e duradouro',
      'Técnicas modernas',
      'Retoque após 30 dias',
      'Micropigmentação labial',
    ],
    procedures: [
      { name: 'Microblading', image: '/images/servicos/micro/Microblading.webp', imageAlt: 'Microblading de sobrancelhas' },
      { name: 'Micropigmentação Labial', image: '/images/servicos/micro/lips.webp', imageAlt: 'Micropigmentação labial' },
    ],
  },
  {
    id: 'estetica-facial',
    slug: 'estetica-facial',
    title: 'Estética Facial',
    description: 'Tratamentos faciais personalizados para todos os tipos de pele com técnicas modernas e produtos de alta qualidade.',
    shortDescription: 'Pele radiante e cuidada',
    price: 'A partir de R$ 150',
    image: '/images/servicos/facial/FACIAL_HEADER.webp',
    imageAlt: 'Estética facial Mimo',
    benefits: [
      'Limpeza de pele profunda',
      'Tratamentos personalizados',
      'Produtos de alta qualidade',
      'Profissionais especializados',
      'Microagulhamento',
      'Peelings químicos',
    ],
    procedures: [
      { name: 'Limpeza Mimo', image: '/images/servicos/facial/LIMPEZAMIMO.webp', imageAlt: 'Limpeza de pele Mimo' },
      { name: 'Limpeza LED', image: '/images/servicos/facial/LIMPEZALED.webp', imageAlt: 'Limpeza de pele com LED' },
      { name: 'Mimo VIP', image: '/images/servicos/facial/MIMOVIP.webp', imageAlt: 'Tratamento facial Mimo VIP' },
      { name: 'Mimo Diamante', image: '/images/servicos/facial/MIMODIAMANTE.webp', imageAlt: 'Tratamento facial Mimo Diamante' },
      { name: 'Diamante', image: '/images/servicos/facial/DIAMANTE.webp', imageAlt: 'Tratamento facial com diamante' },
      { name: 'Peeling Químico', image: '/images/servicos/facial/QUIMICO.webp', imageAlt: 'Peeling químico' },
      { name: 'Microagulhamento', image: '/images/servicos/facial/microagulhamento.webp', imageAlt: 'Microagulhamento facial' },
      { name: 'Limpeza Microagulhamento', image: '/images/servicos/facial/limpezamicroagulhamento.webp', imageAlt: 'Limpeza com microagulhamento' },
      { name: 'Peeling de Cristal', image: '/images/servicos/facial/peeling-de-cristaL.webp', imageAlt: 'Peeling de cristal' },
      { name: 'Depilação Egípcia', image: '/images/servicos/facial/depilacao_egipcia.webp', imageAlt: 'Depilação egípcia' },
    ],
  },
  {
    id: 'estetica-corporal',
    slug: 'estetica-corporal',
    title: 'Estética Corporal',
    description: 'Tratamentos corporais para bem-estar e cuidados com o corpo com técnicas modernas e equipamentos de última geração.',
    shortDescription: 'Cuidados completos para o corpo',
    price: 'A partir de R$ 200',
    image: '/images/servicos/corporal/CORPORAL_HEADER.webp',
    imageAlt: 'Estética corporal Mimo',
    benefits: [
      'Tratamentos personalizados',
      'Técnicas modernas',
      'Foco em bem-estar',
      'Profissionais especializados',
      'Equipamentos de última geração',
    ],
    procedures: [
      { name: 'Drenagem Modeladora', image: '/images/servicos/corporal/drenamodeladora.webp', imageAlt: 'Drenagem modeladora' },
      { name: 'Drenagem Detox Power', image: '/images/servicos/corporal/drenodetoxpower.webp', imageAlt: 'Drenagem detox power' },
      { name: 'Linfática', image: '/images/servicos/corporal/linfatica.webp', imageAlt: 'Drenagem linfática' },
      { name: 'Mimo Detox', image: '/images/servicos/corporal/mimodetox.webp', imageAlt: 'Mimo Detox' },
      { name: 'Modeladora', image: '/images/servicos/corporal/modeladora.webp', imageAlt: 'Massagem modeladora' },
      { name: 'Relaxante', image: '/images/servicos/corporal/relaxante.webp', imageAlt: 'Massagem relaxante' },
      { name: 'Radiofrequência', image: '/images/servicos/corporal/radiofrequencia.webp', imageAlt: 'Radiofrequência corporal' },
      { name: 'Criofrequência', image: '/images/servicos/corporal/criofrequencia.webp', imageAlt: 'Criofrequência' },
      { name: 'Corrente Russa', image: '/images/servicos/corporal/Corrente-Russa.webp', imageAlt: 'Corrente russa' },
      { name: 'Pump', image: '/images/servicos/corporal/pump.webp', imageAlt: 'Pump corporal' },
      { name: 'Ultrassom', image: '/images/servicos/corporal/ultrassom.webp', imageAlt: 'Ultrassom estético' },
      { name: 'Endermoterapia', image: '/images/servicos/corporal/endermoterapia.webp', imageAlt: 'Endermoterapia' },
      { name: 'Estrias', image: '/images/servicos/corporal/estrias.webp', imageAlt: 'Tratamento de estrias' },
      { name: 'Área Íntima', image: '/images/servicos/corporal/areaintima.webp', imageAlt: 'Tratamento área íntima' },
    ],
  },
]

